---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "VyOS LTS 1.4.x"

on:
  workflow_dispatch:

env:
  VYOS_URL: https://github.com/vyos/vyos-build
  VYOS_BRANCH: sagitta
  VYOS_ARCH: amd64
  VYOS_BUILD_TYPE: release
  # TODO: Add renovate snippet
  VYOS_TAG: 1.4.0-epa1
  # TODO: Add renovate snippet
  SOPS_VERSION: v3.8.1
  # TODO: Add renovate snippet
  VYAML_VERSION: 0.2.5

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: vyos/vyos-build:current
      options: --privileged
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup variables
        id: vars
        shell: bash
        run: |
          VYOS_TAG=${{ env.VYOS_TAG }}
          VYOS_VERSION=${VYOS_TAG%-*}
          echo "tag-name=${VYOS_VERSION}+${{ github.repository_owner }}.${{ vars.VYOS_1_4_LTS_BUILD }}" >> "$GITHUB_OUTPUT"
          echo "iso-name=${VYOS_VERSION}-${{ env.VYOS_ARCH }}+${{ github.repository_owner }}" >> "$GITHUB_OUTPUT"

      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          prefix: ${{ steps.vars.outputs.tag-name }}

      - name: Clone vyos-build
        shell: bash
        run: git clone -b ${{ env.VYOS_TAG }} --depth 1 ${{ env.VYOS_URL }}

      - name: Download sops deb
        uses: robinraju/release-downloader@v1.9
        with:
          repository: getsops/sops
          latest: false
          tag: ${{ env.SOPS_VERSION }}
          fileName: "*amd64.deb"
          out-file-path: vyos-build/packages

      - name: Download vyaml deb
        uses: robinraju/release-downloader@v1.9
        with:
          repository: p3lim/vyaml
          latest: false
          tag: ${{ env.VYAML_VERSION }}
          fileName: "*amd64.deb"
          out-file-path: vyos-build/packages

      - name: Configure
        shell: bash
        working-directory: vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso \
              --architecture ${{ env.VYOS_ARCH }} \
              --build-by ${{ github.repository }} \
              --build-type ${{ env.VYOS_BUILD_TYPE }} \
              --build-comment "VyOS with additional packages" \
              --version ${{ steps.buildnumber.outputs.build_number }} \
              --custom-package "iptables" \
              --custom-package "jo" \
              --custom-package "moreutils" \
              --custom-package "tree" \
              --custom-package "vim"

      - name: Create release with artifact
        uses: ncipollo/release-action@v1
        with:
          token: "${{ steps.app-token.outputs.token }}"
          tag: "v${{ steps.buildnumber.outputs.build_number }}"
          artifacts: "./vyos-build/build/vyos-${{ steps.vars.outputs.iso-name }}.iso"
          artifactErrorsFailBuild: true
          prerelease: false
          body: |
            Official VyOS Changelog:
            https://docs.vyos.io/en/latest/changelog/1.4.html

      # - name: Delete orphaned release
      #   if: "${{ failure() }}"
      #   uses: dev-drprasad/delete-tag-and-release@v0.2.1
      #   env:
      #     GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
      #   with:
      #     tag_name: "v${{ steps.vars.outputs.tag-name }}"
      #     delete_release: true

      # - name: Prune old releases
      #   if: "${{ always() }}"
      #   uses: dev-drprasad/delete-older-releases@v0.3.2
      #   env:
      #     GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
      #   with:
      #     keep_latest: 90
      #     delete_tags: true
      #     delete_tag_pattern: rolling
