---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "VyOS Prune"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  prune:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Prune old releases
        if: "${{ always() }}"
        uses: dev-drprasad/delete-older-releases@v0.3.2
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        with:
          keep_latest: 180
          delete_tags: true
          delete_tag_pattern: rolling
