---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "VyOS Rolling 1.5.x"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

env:
  VYOS_BRANCH: current
  VYOS_TAG: 1.5-rolling

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: vyos/vyos-build:current
      options: --privileged
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup variables
        id: vars
        shell: bash
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "tag-name=${{ env.VYOS_TAG }}-${build_date}" >> "$GITHUB_OUTPUT"
          echo "iso-name=${{ env.VYOS_TAG }}-${build_date}-amd64" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: vyos/vyos-build
          ref: ${{ env.VYOS_BRANCH }}
          fetch-depth: 0

      - name: Download sops deb
        uses: robinraju/release-downloader@v1.9
        with:
          repository: getsops/sops
          latest: true
          fileName: "*amd64.deb"
          out-file-path: packages

      - name: Download vyaml deb
        uses: robinraju/release-downloader@v1.9
        with:
          repository: p3lim/vyaml
          latest: true
          fileName: "*amd64.deb"
          out-file-path: packages

      - name: Configure
        shell: bash
        working-directory: vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso \
              --architecture amd64 \
              --build-by ${{ github.repository }} \
              --build-type release \
              --build-comment "VyOS with additional packages" \
              --version ${{ steps.vars.outputs.tag-name }} \
              --custom-package "iptables" \
              --custom-package "jo" \
              --custom-package "moreutils" \
              --custom-package "tree" \
              --custom-package "vim"

      - name: Create release with artifact
        uses: ncipollo/release-action@v1
        with:
          token: "${{ steps.app-token.outputs.token }}"
          tag: "v${{ steps.vars.outputs.tag-name }}"
          artifacts: "./build/vyos-${{ steps.vars.outputs.iso-name }}.iso"
          artifactErrorsFailBuild: true
          prerelease: true
          body: |
            Official VyOS Changelog:
            https://docs.vyos.io/en/latest/changelog/1.5.html

      - name: Delete orphaned release
        if: "${{ failure() }}"
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        with:
          tag_name: "v${{ steps.vars.outputs.tag-name }}"
          delete_release: true

      - name: Prune old releases
        if: "${{ always() }}"
        uses: dev-drprasad/delete-older-releases@v0.3.2
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        with:
          keep_latest: 90
          delete_tags: true
          delete_tag_pattern: rolling
